### ISSUE TITLE
Bug: BaseBlock NullpointerException 

### ISSUE THREAD

**Issue by Shibva** [Tau-ri-Dev/JSGMod-1.12.2#292] opened 2023-11-12 07:29 UTC
**Describe the bug**
when copying a Stargate base block of any kind, the game will crash with a lang.NullpointerException

**To Reproduce**
1. place the Stargate base block in creative
2.  use `select block` while holding ctrl (default keybinds CTRL+MIddleClick); this will cause the block with stored NBT to be added to the players inventory
**Expected behavior**
The game to not crash; lel

**Mod version**
4.11.2.4

**Additional context**
this issue is the same plaguing #290 and #291 so fixing this issue will fix those by proxy.
I talked with a few people about it and with their collective efforts, I managed to get some key information on this bug. It is the following:
- It's caused when the client attempts to read blockdata; the client and servers methods of getting NBT are different, the client method is the only one that's causing a NPE, while the server's is acting fine
- the erroring line was added in https://github.com/Tau-ri-Dev/JSGMod-1.12.2/commit/8856f5e1e4259e47f6691cad50b85cbb6291fb3a (found by using Blame) [at this point, the erroring line in this segment of the crash reports stacktrace would be at line [1804](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/commit/8856f5e1e4259e47f6691cad50b85cbb6291fb3a#diff-4291e267849115f26f45dcf6d025d0da5d8b55df90153b4d000549d726d3ec1aR1804)
- It's not caused by another mod; Crash Report was generated in a pure (JSG only) environment and was triggered using an in-game feature [block picking with NBT data save; ctrl+middleClick by default keybinds]
- **It's not really a serialization error**, this may or may not be true but I asked a developer friend of mine to take a look at this they said something about the hashmap that's associated with `gatePosMap` returning as null sometimes (probably because the location is not cached; idk)

Crash Report (Just JSG): 
[crash-2023-11-12_01.20.05-client.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13327439/crash-2023-11-12_01.20.05-client.txt)

**My whole JSG config (as .zip)**
Generated Config (Default) was used 

**why am I reposting this?**
because it's over a silly little bug and after talking about It I decided to attempt to have this bug patched by gathering as much info on it as possible to put a stake through its bugged heart. This is an high-effort Stargate mod and I can see that, and for such I wish to help keep it like that by providing as much detail as I can to increase the odds of it being fixed 

**Anything else?**
just this
![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/38770780/cc3f9d05-8314-4572-a53d-ec5f8761b228)

Hope all of this helps and thanks for taking the time to read this ^w^

**Comment by MineDragonCZ** [comment] 2023-11-12 10:29
Duplicate of #290

**Closed** 2023-11-12 11:02 UTC
Labels: Duplicate, Bug/Issue, Medium priority
