### ISSUE TITLE
Bug: Universe dialer overload

### ISSUE THREAD

**Issue by FamousL** [Tau-ri-Dev/JSGMod-1.12.2#218] opened 2023-01-29 02:20 UTC
**Describe the bug**
Universe dialer rings section can sometimes overload itself with ring destinations

**To Reproduce**
1. Obtain universe dialer
2. setup 5 or so ring platforms within range of each other (though I have had similar issues appear with less)
3. Observe some ring platforms are listed more than once

**Expected behavior**
Each ring platform should only be listed once. - my character is unable to login as the nbt data for the ring platforms is too large.

**Screenshots**
NBT editor data for my character, 
![Screenshot_2023-01-28_21-15-37](https://user-images.githubusercontent.com/27971720/215300738-f8f80280-15bc-46e3-a451-306d98229651.png)

Minecraft does not like... not one bit.
![Screenshot_2023-01-28_21-17-16](https://user-images.githubusercontent.com/27971720/215300757-87ef742b-ceed-4810-925e-6647894add3c.png)

**Mod version**

jsg-1.12.2-4.11.0.3-client

**Additional context**
Mod is running on both a server and client. 

Full mod list, just in case there may be a collision somewhere (All versions at latest available on curseforge as of last week):
Applied Energistics 2
Auto reg lib
Chickenchunks
code chicken lib
cofh core/world
craftweaker2
cxlibrary
cyclic
ender storage
extrautils2
galacticraft core
galacticraft planets
ichunutil
inventory tweaks
jei
jsg
mantle
mekanism
micdoodlecore
morefurnaces
performant
phosphor
pixelmon
psi
redstone flux
roguelike dungeons fnar edition
sync
tconstruct
thermal expansion
thermal foundation
thermal tinkering
unidict
wanionlib
warpbook
xaeros minimap

┆Issue is synchronized with this [Trello card](https://trello.com/c/jDF8nroI) by [Unito](https://www.unito.io)

**Comment by FamousL** [comment] 2023-01-29 02:25
Additional notes that may be helpful, This can act as a banishment from the server of sorts, any time a new dialer, set to rings is given to the player they are immediately ejected and the dialer is saved to their inventory.
(removed the dialer using nbt editor, and made a new one, same issue came up)

**Comment by MineDragonCZ** [comment] 2023-01-29 10:22
Can you send me JSG config, please?

**Comment by FamousL** [comment] 2023-01-30 00:26
Main difference I can point to off hand, is that I expanded the range of the ring platforms to the maximum allowed in the config. 

`# Configuration file

general {
    B:"Check for updates"=true

    # Valid values:
    # SMALL
    # MEDIUM
    # LARGE
    # EXTRA_LARGE
    S:"Stargate size"=MEDIUM

    "stargate config options" {
        D:"Chance of lighting strike that charge a gate"=5.000000237487257E-4

        # THIS OPTION CAN BE OVERRIDE BY SETTING IT IN STARGATE GUI
        B:"Enable burried state for gates"=true

        # Should gate explode when its overheated?
        # This method is not implemented yet!
        B:"Enable gate overheat with explosion"=false

        # Format: "modid:blockid[:meta/*]", for example: 
        # "minecraft:wool:7"
        # "minecraft:stone"
        # "minecraft:concrete:*"
        S:"Kawoosh invincible blocks" <
            minecraft:snow_layer:*
            minecraft:rail:*
            minecraft:golden_rail:*
            minecraft:detector_rail:*
            minecraft:activator_rail:*
            minecraft:carpet:*
            minecraft:stone_pressure_plate:*
            minecraft:wooden_pressure_plate:*
            minecraft:light_weighted_pressure_plate:*
            minecraft:heavy_weighted_pressure_plate:*
         >
        D:"Max stargate heat"=83400.0

        # Min: 0
        # Max: 2147483647
        I:"Orlin's gate max open count"=2

        # Below this biome temperature the gate will receive frosty texture.
        # Set to negative value to disable.
        D:"Temperature threshold for frosty overlay"=0.10000000149011612

        # Min: 0
        # Max: 64
        I:"Universe dialer max horizontal reach radius"=10
        I:"Universe dialer nearby radius"=1024

        ##########################################################################################################
        # biome overlay biome matches
        #--------------------------------------------------------------------------------------------------------#
        # This check comes last (after block is directly under sky (except Nether) and temperature is high enough).
        # You can disable the temperature check by setting it to a negative value.
        # Format: "modid:biomename", for example: 
        # "minecraft:dark_forest"
        # "minecraft:forest"
        ##########################################################################################################

        "biome overlay biome matches" {
            S:AGED <
             >
            S:FROST <
             >
            S:MOSSY <
                minecraft:jungle
                minecraft:jungle_hills
                minecraft:jungle_edge
                minecraft:mutated_jungle
                minecraft:mutated_jungle_edge
             >
            S:NORMAL <
             >
            S:SOOTY <
                minecraft:hell
             >
        }

        ##########################################################################################################
        # biome overlay override blocks
        #--------------------------------------------------------------------------------------------------------#
        # Format: "modid:blockid[:meta]", for example: 
        # "minecraft:wool:7"
        # "minecraft:stone"
        ##########################################################################################################

        "biome overlay override blocks" {
            S:AGED <
                minecraft:cobblestone
             >
            S:FROST <
                minecraft:ice
             >
            S:MOSSY <
                minecraft:vine
             >
            S:NORMAL <
                minecraft:stone
             >
            S:SOOTY <
                minecraft:coal_block
             >
        }

    }

    "event horizon config options" {
        # Changing this option will require you to reload resources manually.
        # Just restart your game
        B:"Disable animated Event Horizon"=false
        B:"Disable new kawoosh model (from 4.11.0.0)"=false
        B:"Enable wrong side killing"=true
        D:"Unstable Event Horizon chance of death"=0.07000000029802322
    }

    "dialing/incoming options" {
        # If the incoming animations of gates generate issues, set it to false
        # THIS OPTION CAN BE OVERRIDE BY SETTING IT IN STARGATE GUI
        B:"Allow incoming animations"=true

        # If target gate is dialing and this option is set to true,
        # the target gate stop dialing and open incoming wormhole.
        # If this is set to false and the dialed gate dialing address,
        # the connection will not established.
        # If it cause issues, set it to false.
        B:"Connect to dialing gate"=true

        # THIS OPTION CAN BE OVERRIDE BY SETTING IT IN STARGATE GUI
        B:"Enable fast dialing of gates"=true

        # Enable opening last chevron while dialing milkyway gate with dhd
        # THIS OPTION CAN BE OVERRIDE BY SETTING IT IN STARGATE GUI
        B:"Enable opening last chevron while dialing with dhd"=true

        # Speed up dialing with computer on MW and UNI gates
        B:"Faster MilkyWay and Universe gates computer dial"=false

        # If u want to dial UNI-UNI only with seven symbols (interdimensional for example), set this to true
        B:"Need only 7 symbols between Uni gates"=true

        # Change this to true, if you want to use 8 chevrons between pegasus and milkyway gates
        B:"Use 8 chevrons between MW and PG gates"=true
    }

    "iris/shield config options" {
        # Set it to true, if u want to bypass
        # shield/iris damage by creative gamemode
        B:"Allow creative bypass"=false
        B:"Can iris destroy blocks"=false

        # Should iris break when its overheated?
        B:"Enable iris overheat collapse"=true

        # If set to 'false' player get killed by iris on entering event horizon
        B:"Iris kills at destination"=true
        D:"Max titanium iris heat"=1668.0
        D:"Max trinium iris heat"=3336.0

        # Min: 0
        # Max: 32
        I:"Maximum iris code length"=9

        # Energy/tick used for make shield closed
        # Min: 0
        # Max: 2147483647
        I:"Shield power draw"=500

        # Durability of Titanium iris
        # set it to 0, if u want to make it unbreakable
        # Min: 0
        # Max: 2147483647
        I:"Titanium iris durability"=500

        # Durability of Trinium iris
        # set it to 0, if u want to make it unbreakable
        # Min: 0
        # Max: 2147483647
        I:"Trinium iris durability"=1000

        # 0 - disables unbreaking on iris
        # 100 - unbreaking makes iris unbreakable
        # Min: 0
        # Max: 100
        I:"Unbreaking chance per level"=10
    }

    "dhd config options" {
        # When capacity upgrade is placed in the DHD,
        # then multiply internal capacity by this number
        # Min: 1.0
        # Max: 5.0
        D:"Capacity upgrade multiplier"=2.0

        # Min: 0.0
        # Max: 1.0
        D:"Cold fusion reactor activation energy level"=0.4

        # Min: 0.0
        # Max: 1.0
        D:"Cold fusion reactor deactivation energy level"=0.98

        # Min: 1
        # Max: 2147483647
        I:"DHD range's radius horizontal"=25

        # Min: 1
        # Max: 2147483647
        I:"DHD range's radius vertical"=15

        # Min: 1
        # Max: 2147483647
        I:"DHD's max fluid capacity"=16000

        # Energy per 1mB is multiplied by this
        # when efficiency upgrade is placed in the DHD
        # Min: 1.0
        # Max: 5.0
        D:"Efficiency upgrade multiplier"=1.399999976158142

        # THIS OPTION CAN BE OVERRIDE BY SETTING IT IN STARGATE GUI
        B:"Enable press sound when dialing with computer"=false

        # Min: 1
        # Max: 2147483647
        I:"Energy per 1mB Naquadah"=10240

        # Energy per 1mB is multiplied by this
        # Consumed mB/t is equal to this
        # Min: 1
        # Max: 2147483647
        I:"Generation multiplier"=1
    }

    "transport rings options" {
        B:"Ignore rings check for blocks to replace"=false

        # Min: 1
        # Max: 256
        I:"Rings range's radius horizontal"=256

        # Min: 1
        # Max: 256
        I:"Rings vertical reach"=256
    }

    "power draw options" {
        # THIS OPTION CAN BE OVERRIDE BY SETTING IT IN STARGATE GUI
        I:"Capacitors supported by Universe gates"=0

        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Orlin's gate energy multiplier"=2.0

        # Specifies the multiplier of power needed to keep the gate alive
        # when 8-symbols address is dialed
        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Stargate eight symbols address power mul"=1.2999999523162842

        # Seconds of energy left before gate becomes unstable
        # Min: 1
        # Max: 2147483647
        I:"Stargate instability threshold"=20

        # Specifies the multiplier of power needed to keep the gate alive
        # when 9-symbols address is dialed
        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Stargate nine symbols address power mul"=1.7000000476837158

        # Min: 0
        # Max: 2147483647
        I:"Stargate wormhole open power draw"=4608

        # Min: 0
        # Max: 2147483647
        I:"Stargate wormhole sustain power draw"=2

        # Min: 0
        # Max: 2147483647
        I:"Stargate's internal buffer size"=71280000

        # Min: 1
        # Max: 2147483647
        I:"Stargate's max power throughput"=26360

        # Energy extracted from rings every tick when they are active (calculated by distance from these rings)
        I:"Transport Rings active power draw"=2

        # Energy extracted from rings when they teleport LIVING entity (not drop)
        # Min: 0
        # Max: 2147483647
        I:"Transport Rings teleport power draw"=640

        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Universe gate energy multiplier"=1.5
        I:"ZPM capacity (RF)"=2000000000

        # Min: 1
        # Max: 2147483647
        I:"ZPMHub's max power throughput"=104360
    }

    "debug options" {
        B:"Check gate merge"=true
        B:"Log debug messages as info"=false
        B:"Render bounding boxes"=false
        B:"Render invisible blocks"=false
        B:"Render whole kawoosh bounding box"=false
        B:"Show loading textures in log"=false
    }

    "mysterious page options" {
        # Min: 0.0
        # Max: 1.0
        D:"Chance of despawning DHD"=0.05

        # Min: 1
        # Max: 30000000
        I:"Max overworld XZ-coords generation"=30000

        # Min: 1
        # Max: 30000000
        I:"Min overworld XZ-coords generation"=15000

        # Min: 0
        # Max: 2147483647
        I:"Mysterious page cooldown"=40
    }

    "notebook pages options" {
        B:"Enable hint when dialing on DHDs with notebook page"=true

        # Greater values render the Page more to the center of the screen, smaller render it closer to the borders.
        # 0 - for standard 16:9 (default),
        # 0.2 - for 4:3.
        D:"Notebook Page offset"=0.0

        # Min: 0.0
        # Max: 1.0
        D:"Notebook page Glyph transparency"=0.75
    }

    "autoclose options" {
        B:"Autoclose enabled"=true

        # Min: 1
        # Max: 300
        I:"Seconds to autoclose with no players nearby"=5
    }

    "open time limit config" {
        # What happens after gate's open time reaches limit?
        # Valid values:
        # DISABLED
        # CLOSE_GATE
        # DRAW_MORE_POWER
        S:"Gate open time limit mode"=DRAW_MORE_POWER

        # (in seconds (2280 = 38 minutes))
        # Min: 5
        # Max: 3000
        I:"Maximum seconds of gate should be open"=240

        # Min: 0
        # Max: 50000
        I:"Power draw after opened time limit"=10000
    }

    "beamer options" {
        B:"Damage entities in a beam"=true
        B:"Destroy blocks in a beam"=true

        # Min: 1
        # Max: 2147483647
        I:"Energy buffer capacity"=17820000

        # Min: 1
        # Max: 2147483647
        I:"Energy buffer max transfer"=26360

        # Min: 1
        # Max: 2147483647
        I:"Energy/tick needed to keep laser alive"=16384

        # Min: 1
        # Max: 2147483647
        I:"Fluid buffer capacity"=60000

        # Min: 1
        # Max: 2147483647
        I:"Fluid max transfer"=100

        # Min: 1
        # Max: 2147483647
        I:"Interval of signals being send to OC about transfers (in ticks)"=20

        # Min: 1
        # Max: 2147483647
        I:"Item max transfer"=4

        # Min: 3
        # Max: 50
        I:"Max gate-beamer distance"=10
        B:"Should the beam be responsive to fluid color"=true
    }

    "audio/video" {
        # Min: 0.0
        # Max: 1.0
        D:"JSG volume"=1.0
        B:"Render EHs even if they are not rendering"=true

        # Render light of some textures.
        # Disable this if it causes lags.
        B:"Render emissive textures"=true
        B:"Render not placed blocks of s stargate"=true
    }

    "point of origin options" {
        # Specifies Point Of Origins that were added by any resource pack.
        # This options is required to load all models of added origins!
        # Format: "id:name", for example: 
        # "6:Tollan"
        # "7:P4X-256"
        # !DO NOT CHANGE ANYTHING IF YOU DON'T KNOW WHAT ARE YOU DOING!
        S:"Custom added points of origin" <
         >
        B:"Enable different Point Of Origins for MW gate"=true
    }

    "ore generator config" {
        # Do you want to spawn naquadah ores in the Nether?
        B:"Enable Naquadah ore generation"=true

        # Do you want to spawn titanium ores in the Overworld?
        B:"Enable Titanium ore generation"=true

        # Do you want to spawn trinium ores in the End?
        B:"Enable Trinium ore generation"=true
        I:"Naquadah max veins in chunk"=16
        I:"Naquadah vein size"=8
        I:"Titanium max veins in chunk"=16
        I:"Titanium vein size"=4
        I:"Trinium max veins in chunk"=16
        I:"Trinium vein size"=4
    }

    "stargate generator config" {
        # Min: 0.0
        # Max: 1.0
        D:"Chance of generating stargates in End"=7.000000186963007E-5

        # Min: 0.0
        # Max: 1.0
        D:"Chance of generating stargates in Overworld"=9.999999747378752E-5

        # Generate stargate in world random.
        B:"Enable random stargate generator"=true

        # Enable generation of structures in the world.
        # This will not disable the stargate generation!
        B:"Enable random structures generator"=true
    }

    "mainmenu config" {
        # Disables showing custom main menu
        # WARNING! - Requires reloading!
        B:"Disable JSG main menu"=true
        B:"Enable changing gate type"=true
        B:"Enable debug mode"=false
        B:"Enable loading music"=true
        B:"Enable sync with minecraft ticks"=false
        B:"Play music in main menu"=true
    }

    "integrations config" {
        # WARNING! - Requires reloading!
        B:"Enable Open Computers integration"=true

        # WARNING! - Requires reloading!
        B:"Enable Thermal Expansion integration"=true

        # WARNING! - Requires reloading!
        B:"Enable Tinkers' Construct integration"=true
        I:"OC wireless network range (in blocks)"=20
    }

    "random incoming config" {
        # 10 = 1%
        # Min: 1
        # Max: 100
        I:"Chance of spawning"=1

        # Enable random incoming wormholes generator
        # THIS OPTION CAN BE OVERRIDE BY SETTING IT IN STARGATE GUI
        B:"Enable random incoming wormholes"=true

        # Format: "modid:entityid", for example: 
        # "minecraft:zombie"
        # "minecraft:creeper"
        S:"Entities to spawn" <
            minecraft:zombie
            minecraft:skeleton
         >
    }

    "advancements config" {
        # Players in this radius around triggered pos will get Advancement.
        I:"Ranged Advancements radius"=25
    }

    "countdown config" {
        I:"Delay after zero-time (seconds)"=5
        I:"Delay to start dialing after countdown start (seconds)"=5
    }

    "development config" {
        B:"Dev mode"=false
        D:s=1.0
        D:sz=0.0
        B:t1=false
        D:tz=0.0
        D:x=0.0
        D:x2=0.0
        D:y=0.0
        D:y2=0.0
        D:yz=0.0
        D:z=0.0
        D:z2=0.0
    }

}


`

**Comment by FamousL** [comment] 2023-01-30 02:00
Just discovered some new info, looks like breaking the ring platform and replacing it provides a momentary work around, transporting between rings seems to be the key to creating the bug.

**Comment by FamousL** [comment] 2023-01-30 02:48
NBT tile data as recorded from the ring platform "Base" about half an hour after the above screenshot:
`
rendererState: {
	byteArray: [B;0B,0B,0B,0B,0B,0B,-111B,-96B,18B,0B,0B,0B,0B,2B,0B,0B,0B,0B,0B,0B,64B,-50B,-1B,-1B,-13B,15B,0B,0B,0B,5B,0B,0B,0B,5B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,64B,37B,0B,0B,0B,0B,0B,0B,64B,37B,0B,0B,0B,0B,0B,0B,0B,0B,0B,1B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,64B,35B,0B,0B,0B,0B,0B,0B,64B,35B,0B,0B,0B,0B,0B,0B,0B,0B,0B,2B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,64B,33B,0B,0B,0B,0B,0B,0B,64B,33B,0B,0B,0B,0B,0B,0B,0B,0B,0B,3B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,64B,30B,0B,0B,0B,0B,0B,0B,64B,30B,0B,0B,0B,0B,0B,0B,0B,0B,0B,4B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,64B,26B,0B,0B,0B,0B,0B,0B,64B,26B,0B,0B,0B,0B,0B,0B,0B,0B,0B,5B,0B,0B,0B,0B,0B,0B,0B,14B,112B,108B,97B,116B,102B,111B,114B,109B,77B,111B,118B,105B,110B,103B,0B,0B,0B,1B,0B,0B,0B,27B,82B,101B,110B,100B,101B,114B,32B,112B,108B,97B,116B,102B,111B,114B,109B,32B,109B,111B,118B,105B,110B,103B,32B,112B,97B,114B,116B,0B,0B,0B,2B,0B,0B,0B,4B,116B,114B,117B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,4B,116B,114B,117B,101B,0B,0B,0B,0B,0B,0B,0B,1B,0B,0B,0B,12B,112B,108B,97B,116B,102B,111B,114B,109B,66B,97B,115B,101B,0B,0B,0B,1B,0B,0B,0B,25B,82B,101B,110B,100B,101B,114B,32B,112B,108B,97B,116B,102B,111B,114B,109B,32B,98B,97B,115B,101B,32B,112B,97B,114B,116B,0B,0B,0B,2B,0B,0B,0B,4B,116B,114B,117B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,4B,116B,114B,117B,101B,0B,0B,0B,0B,0B,0B,0B,2B,0B,0B,0B,12B,111B,99B,80B,114B,101B,115B,115B,83B,111B,117B,110B,100B,0B,0B,0B,1B,0B,0B,0B,37B,80B,108B,97B,121B,32B,112B,114B,101B,115B,115B,32B,115B,111B,117B,110B,100B,32B,119B,104B,101B,110B,32B,100B,105B,97B,108B,105B,110B,103B,32B,119B,105B,116B,104B,32B,79B,67B,0B,0B,0B,2B,0B,0B,0B,5B,102B,97B,108B,115B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,5B,102B,97B,108B,115B,101B,0B,0B,0B,0B,0B,0B,0B,3B,0B,0B,0B,13B,109B,97B,120B,67B,97B,112B,97B,99B,105B,116B,111B,114B,115B,0B,0B,0B,3B,0B,0B,0B,18B,83B,112B,101B,99B,105B,102B,105B,101B,115B,32B,104B,111B,119B,32B,109B,97B,110B,121B,0B,0B,0B,27B,99B,97B,112B,97B,99B,105B,116B,111B,114B,115B,32B,99B,97B,110B,32B,98B,101B,32B,105B,110B,115B,116B,97B,108B,108B,101B,100B,0B,0B,0B,10B,105B,110B,116B,111B,32B,114B,105B,110B,103B,115B,0B,0B,0B,1B,0B,0B,0B,1B,50B,0B,0B,0B,0B,0B,0B,0B,3B,0B,0B,0B,1B,50B,0B,0B,0B,0B,0B,0B,0B,4B,0B,0B,0B,15B,110B,111B,110B,97B,99B,116B,105B,118B,101B,82B,101B,110B,100B,101B,114B,0B,0B,0B,1B,0B,0B,0B,48B,82B,101B,110B,100B,101B,114B,32B,114B,105B,110B,103B,32B,117B,110B,100B,101B,114B,32B,103B,114B,111B,117B,110B,100B,32B,105B,102B,32B,114B,105B,110B,103B,115B,32B,97B,114B,101B,32B,110B,111B,116B,32B,97B,99B,116B,105B,118B,101B,0B,0B,0B,2B,0B,0B,0B,5B,102B,97B,108B,115B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,5B,102B,97B,108B,115B,101B,0B,0B,0B,0B]
}
excludedSize: 0
ringsMap1: {
	distance: 48.76474136094644d
	address_0: {
		addressLength: 4
		addressSymbol0: 1
		addressSymbol1: 2
		addressSymbol2: 3
		addressSymbol3: 0
		symbolType: 0
	}
	pos: -542054601981952L
	address_1: {
		addressLength: 4
		addressSymbol0: 4
		addressSymbol1: 3
		addressSymbol2: 1
		addressSymbol3: 2
		symbolType: 1
	}
	address_2: {
		addressLength: 4
		addressSymbol0: 3
		addressSymbol1: 5
		addressSymbol2: 4
		addressSymbol3: 8
		symbolType: 2
	}
	name: ""
	ringsDistance: 2
}
energyStorage: {
	energy: 12120491
}
ringsMap2: {
	distance: 58.31809324729333d
	address_0: {
		addressLength: 4
		addressSymbol0: 2
		addressSymbol1: 4
		addressSymbol2: 3
		addressSymbol3: 1
		symbolType: 0
	}
	pos: -541230169587637L
	address_1: {
		addressLength: 4
		addressSymbol0: 2
		addressSymbol1: 4
		addressSymbol2: 3
		addressSymbol3: 1
		symbolType: 1
	}
	address_2: {
		addressLength: 4
		addressSymbol0: 1
		addressSymbol1: 3
		addressSymbol2: 8
		addressSymbol3: 2
		symbolType: 2
	}
	name: ""
	ringsDistance: 2
}
targetRingsPos: 0L
ringsMap0: {
	distance: 44.429719783046124d
	address_0: {
		addressLength: 4
		addressSymbol0: 4
		addressSymbol1: 2
		addressSymbol2: 0
		addressSymbol3: 3
		symbolType: 0
	}
	pos: -539855712944086L
	address_1: {
		addressLength: 4
		addressSymbol0: 4
		addressSymbol1: 2
		addressSymbol2: 3
		addressSymbol3: 1
		symbolType: 1
	}
	address_2: {
		addressLength: 4
		addressSymbol0: 8
		addressSymbol1: 4
		addressSymbol2: 3
		addressSymbol3: 7
		symbolType: 2
	}
	name: ""
	ringsDistance: 2
}
itemHandler: {
	Size: 10
	Items: {
		[0]: {
			Slot: 4
			id: "jsg:capacitor_block"
			Count: 1b
			tag: {
				energy: 17772890
			}
			Damage: 0s
		}
	}
}
scheduledTasks: {
	size: 0
}
ringsMapLength: 3
ringsData: {
	address_0: {
		addressLength: 4
		addressSymbol0: 0
		addressSymbol1: 2
		addressSymbol2: 1
		addressSymbol3: 4
		symbolType: 0
	}
	pos: -550027671896033L
	address_1: {
		addressLength: 4
		addressSymbol0: 3
		addressSymbol1: 2
		addressSymbol2: 1
		addressSymbol3: 4
		symbolType: 1
	}
	address_2: {
		addressLength: 4
		addressSymbol0: 6
		addressSymbol1: 8
		addressSymbol2: 4
		addressSymbol3: 7
		symbolType: 2
	}
	name: "Base"
	ringsDistance: 2
}
busy: 0b
x: -2001
teleportListSize: 0
initiating: 0b
y: 45
z: 31
id: "jsg:transportrings_goauld_block"
config: {
	Option4: {
		commentSize: 1
		possibleValuesLength: 0
		maxInt: -1
		comment0: "Render ring under ground if rings are not active"
		minInt: -1
		defaultValue: "false"
		id: 4
		label: "nonactiveRender"
		type: 2
		value: "false"
	}
	Option3: {
		commentSize: 3
		possibleValuesLength: 0
		comment2: "into rings"
		comment1: "capacitors can be installed"
		maxInt: 3
		comment0: "Specifies how many"
		minInt: 0
		defaultValue: "2"
		id: 3
		label: "maxCapacitors"
		type: 1
		value: "2"
	}
	Option2: {
		commentSize: 1
		possibleValuesLength: 0
		maxInt: -1
		comment0: "Play press sound when dialing with OC"
		minInt: -1
		defaultValue: "false"
		id: 2
		label: "ocPressSound"
		type: 2
		value: "false"
	}
	Option1: {
		commentSize: 1
		possibleValuesLength: 0
		maxInt: -1
		comment0: "Render platform base part"
		minInt: -1
		defaultValue: "true"
		id: 1
		label: "platformBase"
		type: 2
		value: "true"
	}
	Option0: {
		commentSize: 1
		possibleValuesLength: 0
		maxInt: -1
		comment0: "Render platform moving part"
		minInt: -1
		defaultValue: "true"
		id: 0
		label: "platformMoving"
		type: 2
		value: "true"
	}
	Size: 5
}
`

**Comment by MineDragonCZ** [comment] 2023-02-01 20:11
So overloading can be probably caused by this:
![image](https://user-images.githubusercontent.com/78699120/216152628-7a84846d-6e2e-46e1-bd77-610ac02ca29b.png)

It loops about 256*256 blocks, so it can be hard to process by your PC

**Comment by FamousL** [comment] 2023-02-01 20:18
I will give that a try, maybe the porting in conjunction with the distance is playing with it in a way that i am not seeing.

**Comment by FamousL** [comment] 2023-02-02 02:04
broke the platform, placed it back down, ran a few transports, and it happened again...
![Screenshot_2023-02-01_21-03-56](https://user-images.githubusercontent.com/27971720/216213194-df47e8de-90c8-41b5-809c-9359907631e7.png)

**Comment by FamousL** [comment] 2023-02-14 17:19
I cannot seem to get this error to appear in 4.11.0.4. issue may no longer be present.

**Comment by MineDragonCZ** [comment] 2023-02-25 10:32
> I cannot seem to get this error to appear in 4.11.0.4. issue may no longer be present.

Thanks. Closing issue

**Closed by MineDragonCZ** 2023-02-25 10:32 UTC
Labels: Bug/Issue, Can not reproduce
