### ISSUE TITLE
Bug: Ring transport Error

### ISSUE THREAD

**Issue by FamousL** [Tau-ri-Dev/JSGMod-1.12.2#228] opened 2023-02-21 19:07 UTC
**Describe the bug**
Ring platform teleports to unrelated area, seems to be only the one platform, i can port *to* but any port *from* this platform causes issues. 

**To Reproduce**
Unknown, ring platforms in play were working perfectly. The last configuration change on the server is adding Open Computers

**Expected behavior**
Ring platforms should teleport to each other not to an unrelated area.

**Screenshots**

Intended destination:
![2023-02-21_13 59 30](https://user-images.githubusercontent.com/27971720/220435993-330a746b-fe68-4987-b68e-4e5e55a08075.png)

Universe dialer set to send me to that place:
![2023-02-21_14 00 28](https://user-images.githubusercontent.com/27971720/220436055-7ceb2f9e-0410-4753-9d8a-46e21f3a1945.png)

Where I ended up:
![2023-02-21_14 00 35](https://user-images.githubusercontent.com/27971720/220436101-bdd6ebb9-86f2-444b-bba6-70a948fee523.png)

**Mod version**
jsg-1.12.2-4.11.0.5-client.jar

**Comment by FamousL** [comment] 2023-02-21 19:29
https://youtu.be/5ZZ5YDXe50g shows a bit more of this

**Comment by MineDragonCZ** [comment] 2023-02-21 20:55
Can I see a configuration of the _bugged_ rings, please?

**Comment by FamousL** [comment] 2023-02-22 00:28
nbt block data

rendererState: {
	byteArray: [B;0B,0B,0B,0B,0B,2B,-69B,-7B,124B,0B,0B,0B,0B,2B,0B,0B,0B,0B,0B,0B,0B,30B,-1B,-1B,-1B,-1B,0B,0B,0B,1B,0B,0B,0B,5B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,0B,64B,37B,0B,0B,0B,0B,0B,0B,64B,37B,0B,0B,0B,0B,0B,0B,0B,0B,0B,1B,0B,0B,0B,0B,0B,0B,0B,2B,-69B,-7B,-12B,0B,0B,0B,0B,0B,0B,0B,0B,64B,35B,0B,0B,0B,0B,0B,0B,0B,0B,0B,2B,0B,0B,0B,0B,0B,0B,0B,2B,-69B,-7B,-17B,0B,0B,0B,0B,0B,0B,0B,0B,64B,33B,0B,0B,0B,0B,0B,0B,0B,0B,0B,3B,0B,0B,0B,0B,0B,0B,0B,2B,-69B,-7B,-22B,0B,0B,0B,0B,0B,0B,0B,0B,64B,30B,0B,0B,0B,0B,0B,0B,0B,0B,0B,4B,0B,0B,0B,0B,0B,0B,0B,2B,-69B,-7B,-27B,0B,0B,0B,0B,0B,0B,0B,0B,64B,26B,0B,0B,0B,0B,0B,0B,0B,0B,0B,5B,0B,0B,0B,0B,0B,0B,0B,14B,112B,108B,97B,116B,102B,111B,114B,109B,77B,111B,118B,105B,110B,103B,0B,0B,0B,1B,0B,0B,0B,27B,82B,101B,110B,100B,101B,114B,32B,112B,108B,97B,116B,102B,111B,114B,109B,32B,109B,111B,118B,105B,110B,103B,32B,112B,97B,114B,116B,0B,0B,0B,2B,0B,0B,0B,4B,116B,114B,117B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,4B,116B,114B,117B,101B,0B,0B,0B,0B,0B,0B,0B,1B,0B,0B,0B,12B,112B,108B,97B,116B,102B,111B,114B,109B,66B,97B,115B,101B,0B,0B,0B,1B,0B,0B,0B,25B,82B,101B,110B,100B,101B,114B,32B,112B,108B,97B,116B,102B,111B,114B,109B,32B,98B,97B,115B,101B,32B,112B,97B,114B,116B,0B,0B,0B,2B,0B,0B,0B,4B,116B,114B,117B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,4B,116B,114B,117B,101B,0B,0B,0B,0B,0B,0B,0B,2B,0B,0B,0B,12B,111B,99B,80B,114B,101B,115B,115B,83B,111B,117B,110B,100B,0B,0B,0B,1B,0B,0B,0B,37B,80B,108B,97B,121B,32B,112B,114B,101B,115B,115B,32B,115B,111B,117B,110B,100B,32B,119B,104B,101B,110B,32B,100B,105B,97B,108B,105B,110B,103B,32B,119B,105B,116B,104B,32B,79B,67B,0B,0B,0B,2B,0B,0B,0B,5B,102B,97B,108B,115B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,5B,102B,97B,108B,115B,101B,0B,0B,0B,0B,0B,0B,0B,3B,0B,0B,0B,13B,109B,97B,120B,67B,97B,112B,97B,99B,105B,116B,111B,114B,115B,0B,0B,0B,3B,0B,0B,0B,18B,83B,112B,101B,99B,105B,102B,105B,101B,115B,32B,104B,111B,119B,32B,109B,97B,110B,121B,0B,0B,0B,27B,99B,97B,112B,97B,99B,105B,116B,111B,114B,115B,32B,99B,97B,110B,32B,98B,101B,32B,105B,110B,115B,116B,97B,108B,108B,101B,100B,0B,0B,0B,10B,105B,110B,116B,111B,32B,114B,105B,110B,103B,115B,0B,0B,0B,1B,0B,0B,0B,1B,50B,0B,0B,0B,0B,0B,0B,0B,3B,0B,0B,0B,1B,50B,0B,0B,0B,0B,0B,0B,0B,4B,0B,0B,0B,15B,110B,111B,110B,97B,99B,116B,105B,118B,101B,82B,101B,110B,100B,101B,114B,0B,0B,0B,1B,0B,0B,0B,48B,82B,101B,110B,100B,101B,114B,32B,114B,105B,110B,103B,32B,117B,110B,100B,101B,114B,32B,103B,114B,111B,117B,110B,100B,32B,105B,102B,32B,114B,105B,110B,103B,115B,32B,97B,114B,101B,32B,110B,111B,116B,32B,97B,99B,116B,105B,118B,101B,0B,0B,0B,2B,0B,0B,0B,5B,102B,97B,108B,115B,101B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,-1B,0B,0B,0B,5B,102B,97B,108B,115B,101B,0B,0B,0B,0B]
}
linkedController: -549752592662490L
excludedSize: 0
energyStorage: {
	energy: 0
}
targetRingsPos: 0L
itemHandler: {
	Size: 10
	Items: {
	}
}
scheduledTasks: {
	size: 0
}
linkId: 235
ringsMapLength: 0
ringsData: {
	address_0: {
		addressLength: 4
		addressSymbol0: 0
		addressSymbol1: 2
		addressSymbol2: 1
		addressSymbol3: 4
		symbolType: 0
	}
	pos: -550027671896033L
	address_1: {
		addressLength: 4
		addressSymbol0: 3
		addressSymbol1: 2
		addressSymbol2: 1
		addressSymbol3: 4
		symbolType: 1
	}
	address_2: {
		addressLength: 4
		addressSymbol0: 6
		addressSymbol1: 8
		addressSymbol2: 4
		addressSymbol3: 7
		symbolType: 2
	}
	name: ""
	ringsDistance: 2
}
busy: 0b
x: -2001
teleportListSize: 0
initiating: 0b
y: 45
ForgeCaps: {
}
z: 31
id: "jsg:transportrings_goauld_block"
config: {
	Size: 0
}

**Comment by FamousL** [comment] 2023-02-22 00:28
rings config file:

# Configuration file

transportrings {

    ##########################################################################################################
    # mechanics
    #--------------------------------------------------------------------------------------------------------#
    # Rings Mechanics settings
    ##########################################################################################################

    mechanics {
        # SIDE: SERVER
        B:"Ignore rings check for blocks to replace"=false

        # SIDE: SERVER
        # Min: 1
        # Max: 256
        I:"Rings range's radius horizontal"=256

        # SIDE: SERVER
        # Min: 1
        # Max: 256
        I:"Rings vertical reach"=256
    }

    ##########################################################################################################
    # power
    #--------------------------------------------------------------------------------------------------------#
    # Rings Power settings
    ##########################################################################################################

    power {
        # Energy extracted from rings every tick when they are active (calculated by distance from these rings)
        # SIDE: SERVER
        # Min: 0
        # Max: 100
        I:"Transport Rings active power draw"=2

        # Energy extracted from rings when they teleport LIVING entity (not drop)
        # SIDE: SERVER
        # Min: 0
        # Max: 25600
        I:"Transport Rings teleport power draw"=640
    }

}

**Comment by MineDragonCZ** [comment] 2023-02-24 16:08
So from what i see, the whole config of the rings is not here. Idk why. 

Try to rebuild the rings and if the issue is still happening try to enter creative mode (if you are on a server, contact admin) and open the gui of the bugged rings. Then try to change something in the tile config of the rings and close the gui.

**Comment by FamousL** [comment] 2023-02-24 16:18
Looks like that cleared it, apologies for the rename, your change didn't show up on my end until after I updated the name of the thread.

**Comment by MineDragonCZ** [comment] 2023-02-24 16:20
> Looks like that cleared it, apologies for the rename, your change didn't show up on my end until after I updated the name of the thread.

Nevermind :)

**Comment by MineDragonCZ** [comment] 2023-04-29 15:29
Problem is still here?

**Comment by MineDragonCZ** [comment] 2023-05-14 08:47
Closing because it should be fixed and author not responding...

**Closed by MineDragonCZ** 2023-05-14 08:47 UTC
Labels: Bug/Issue, Medium priority, Waiting on info, Can not reproduce
