### ISSUE TITLE
Bug: [CrafTweaker] NullPointerException when trying to read data from a block 

### ISSUE THREAD

**Issue by Shibva** [Tau-ri-Dev/JSGMod-1.12.2#291] opened 2023-11-10 08:35 UTC
**Describe the bug**
when using a script (Provided below) will cause a NullPointException to be thrown when it previously dint in 
 4.11.1.0

**To Reproduce**
1. Install CraftTweaker and Script Below (configuration will be slightly modified for the sake of reducing mods)
2. Open a new world in create
3. place a stargate base block of any kind (except for orlin, this one is not used by the script since its not world-generated :P)
4. go into survival
5. mine with anything (for the scrip ill send you it will be set as a iron hoe, golden axe, and diamond shovel as valid breaking tools; this is just for limited mod tested to take place without the need to add additional mods I swear)

**Expected behavior**
The script itself no longer producing a NullPointerException whenever it ties to mine a block with this script like it did in  4.11.1.0

**Screenshots**
the erroing portion of the CT log (tip: if you need to access this look inside the logs folder)
![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/38770780/99ccc082-386e-4a9f-98d0-3ef3db6ee0b8)

**Mod version**
 4.11.2.3

**Additional context**
The Script is made to allow for world-generated stargates to be unmineable unless you have a specific tool(s) that accept it; if you don't have it then it will cancel the onBlockBreaking event that takes place when mining it. This does not happen If a tag `isPlayerPlaced: true` is present; this is done by using a clever trick by writing it inside of ForgeData when the block is placed by a player. To be real with you it was working before  4.11.2.0 and I was proud of it since it took me a long time to figure out a way for this to work lel.

It also should be noted that the gate base blocks are the only blocks having this issue, as the other blocks do not have this problem.

Script (minor modifications from the actual; changes only what the valid tools are **[iron_hoe, gold_axe, diamond_shovel]** (place into the slots folder once you run an instance with CT once)
[gated_stargate_salvage_protecter_V1.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13317257/gated_stargate_salvage_protecter_V1.zip)

**My whole JSG config (as .zip)**
[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13317176/jsg.zip)

**Comment by MineDragonCZ** [comment] 2023-11-10 13:30
This issue is probably caused by crafttweaker itself. Idk why its in this version and the old one no. Maybe its random...
I can't fi it, because its problem somehow with NBT serialization.

**Comment by MineDragonCZ** [comment] 2023-11-10 13:33
also its duplicate of #290

**Comment by Shibva** [comment] 2023-11-10 16:35
It could be caused by some change you made to the base block itself

It only does this if you mine it

By guess is that it's updating while it's being mined for some reason

**Comment by Shibva** [comment] 2023-11-10 18:27
@MineDragonCZ I wonder if it has to do with the recent implementation of being able to wrench a block

Whatever it is; my educated guess is that a change that you made to the `baseBlock` between those versions cause the behavior of the block to update the entirety of its data while it's being mined; because it essentially all boils down to this for the script: the block data itself briefly does not exist while it's being broken and that's what's causing it to throw a NPE because for that brief moment, it does not exist.

Anyhow, thanks for looking into this, even if it doesn't yield anything 

If you like what my script is doing by prohibiting world generated, nonplayer placed gates when feel free to implement it, because essentially this script was supposed to use as a utility

**Comment by MR-Spagetty** [comment] 2023-11-10 23:27
> also its duplicate of #290 

No its not #290 was a different issue shibva saw was similar to their own

**Comment by Shibva** [comment] 2023-11-11 01:53
It appears to be very similar however @MR-Spagetty 

If you look at the line in their crash report it's writing to NBT. It could be because of updates that that crash was happening in #290

In my situation, it was reading it and technically it's not a crash in my situation, but it does prevent the script from working correctly because it's throwing a NPE with that block in particular

**Comment by Shibva** [comment] 2023-11-11 01:59
While it is two different issues; they're all being caused by the same thing I believe; something that is causing the NBT data to be absent; it's acting like it wiping and then re-writing itself whenever it updates or something

**Closed** 2023-11-12 11:02 UTC
Labels: Duplicate, Bug/Issue
